version: '3'

services:
  web:
    build: .
    command: gunicorn shop_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_db_user
      - POSTGRES_PASSWORD=dev_db_password
      - POSTGRES_DB=dev_db
volumes:
  postgres_data: