# Generated by Django 4.1.7 on 2023-02-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='None.jpg', upload_to='', verbose_name='image'),
        ),
    ]
